# Generated by Django 5.2.2 on 2026-02-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_parent_initial_password_parent_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='methodpackage',
            name='content_blocks',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
