# Generated by Django 5.2.2 on 2026-02-14 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_event_feedpost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='initial_password',
            field=models.CharField(blank=True, help_text='Сгенерированный пароль (показывается один раз, попросите сменить).', max_length=32),
        ),
        migrations.AddField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Админ'), ('methodist', 'Методист'), ('parent', 'Родитель'), ('student', 'Ребенок'), ('teacher', 'Учитель')], max_length=20),
        ),
        migrations.CreateModel(
            name='MethodAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateField(blank=True, null=True)),
                ('can_edit', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('todo', 'К выполнению'), ('in_progress', 'В работе'), ('review', 'На проверке'), ('done', 'Готово')], default='todo', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_method_assignments', to=settings.AUTH_USER_MODEL)),
                ('method_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='messenger.methodpackage')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='method_assignments', to='messenger.teacher')),
            ],
            options={
                'ordering': ['deadline', '-created_at'],
                'unique_together': {('method_package', 'teacher')},
            },
        ),
    ]
