# Generated by Django 5.2.2 on 2026-02-19 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0005_teacher_initial_password_teacher_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduleslot',
            options={'ordering': ['group', 'lesson_date', 'weekday', 'start_time', 'lesson_number']},
        ),
        migrations.AlterUniqueTogether(
            name='scheduleslot',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='scheduleslot',
            name='lesson_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduleslot',
            name='moved_from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheduleslot',
            name='lesson_number',
            field=models.PositiveSmallIntegerField(help_text='Порядковый номер занятия'),
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('title', models.CharField(blank=True, default='Праздничный день', max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='messenger.group')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
