# Generated by Django 5.2.11 on 2026-02-20 07:56

import django.db.models.deletion
from django.db import migrations, models


def bootstrap_chat_rooms(apps, schema_editor):
    Group = apps.get_model('messenger', 'Group')
    ChatRoom = apps.get_model('messenger', 'ChatRoom')
    Message = apps.get_model('messenger', 'Message')

    students_room_by_group = {}
    for group in Group.objects.all().iterator():
        ChatRoom.objects.get_or_create(group_id=group.id, room_type='parents')
        room, _ = ChatRoom.objects.get_or_create(group_id=group.id, room_type='students')
        students_room_by_group[group.id] = room.id

    for message in Message.objects.filter(room__isnull=True).iterator():
        room_id = students_room_by_group.get(message.group_id)
        if room_id:
            Message.objects.filter(id=message.id).update(room_id=room_id)


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0007_subject_lessontopic_scheduleslot_lesson_topic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('parents', 'Родители'), ('students', 'Студенты')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='messenger.group')),
            ],
            options={
                'ordering': ['group', 'room_type'],
                'unique_together': {('group', 'room_type')},
            },
        ),
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messenger.chatroom'),
        ),
        migrations.RunPython(bootstrap_chat_rooms, migrations.RunPython.noop),
    ]
