# Generated by Django 5.2.11 on 2026-02-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0009_message_attachment_message_attachment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='methodpackage',
            name='method_number',
            field=models.PositiveSmallIntegerField(default=1, help_text='Номер методпакета в рамках предмета (1-12).'),
        ),
    ]
