# Generated by Django 5.2.11 on 2026-02-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0011_methodassignmentcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='room_type',
            field=models.CharField(choices=[('parents', 'Родители'), ('students', 'Студенты'), ('management', 'Менеджер и преподаватель')], max_length=16),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_type',
            field=models.CharField(choices=[('teacher', 'Преподаватель'), ('manager', 'Менеджер'), ('parent', 'Родитель'), ('student', 'Ученик'), ('system', 'Система')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Админ'), ('methodist', 'Методист'), ('manager', 'Менеджер учебного процесса'), ('parent', 'Родитель'), ('student', 'Ребенок'), ('teacher', 'Учитель')], max_length=20),
        ),
    ]
